# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import configuration_pb2 as configuration__pb2


class ServerGRPCStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.listen_key = channel.unary_unary(
        '/configuration.ServerGRPC/listen_key',
        request_serializer=configuration__pb2.listenKeyRequest.SerializeToString,
        response_deserializer=configuration__pb2.Empty.FromString,
        )
    self.verify_queue = channel.unary_stream(
        '/configuration.ServerGRPC/verify_queue',
        request_serializer=configuration__pb2.listenKeyRequest.SerializeToString,
        response_deserializer=configuration__pb2.listenKeyReply.FromString,
        )


class ServerGRPCServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def listen_key(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def verify_queue(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ServerGRPCServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'listen_key': grpc.unary_unary_rpc_method_handler(
          servicer.listen_key,
          request_deserializer=configuration__pb2.listenKeyRequest.FromString,
          response_serializer=configuration__pb2.Empty.SerializeToString,
      ),
      'verify_queue': grpc.unary_stream_rpc_method_handler(
          servicer.verify_queue,
          request_deserializer=configuration__pb2.listenKeyRequest.FromString,
          response_serializer=configuration__pb2.listenKeyReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'configuration.ServerGRPC', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
